### ISSUE TITLE
the newest commit is not  '5fba0dd'

### ISSUE THREAD

**Issue by gloddream** [atsushieno/cerbero#3]
should update to “ fd96ef4”？

class Recipe(recipe.Recipe):

    name = 'fluidsynth'
    version = '1.1.6'
    licenses = [License.LGPLv2]
    deps = ['glib']
    remotes = {'origin': 'https://github.com/atsushieno/fluidsynth.git'}
    commit = '5fba0dd'
    srcdir = 'fluidsynth'
    config_sh = './autogen.sh && CFLAGS=-DDEFAULT_SOUNDFONT=NULL ./configure'
    files_libs = ['libfluidsynth']
    files_lang = ['fluidsynth']
    files_devel = [
            'include/fluidsynth',
            'fluidsynth.pc',
            ]

**Comment by atsushieno** [comment]
Thanks, bumped it at 400c643e6807b93606141ff379e4447dbc254049

**Comment by gloddream** [comment]
after update the newest version

get error：


armv7-a -Wl,--fix-cortex-a8 -pthread   -pthread -Wl,-soname -Wl,libfluidsynth.so -o .libs/libfluidsynth.so
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_close: error: undefined reference to 'AAsset_close'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_open: error: undefined reference to 'AAssetManager_open'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_length: error: undefined reference to 'AAsset_getLength'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_position: error: undefined reference to 'AAsset_seek'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_safe_seek_by: error: undefined reference to 'AAsset_seek'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_safe_read: error: undefined reference to 'AAsset_read'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_read: error: undefined reference to 'AAsset_read'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function new_fluid_android_asset_stream_loader: error: undefined reference to 'AAssetManager_fromJava'
collect2: error: ld returned 1 exit status
Makefile:857: recipe for target 'libfluidsynth.la' failed
make[3]: *** [libfluidsynth.la] Error 1
make[3]: Leaving directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src'
Makefile:634: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth'

Recipe 'fluidsynth' failed at the build step 'compile'
