### ISSUE TITLE
after build android fluidsynth.so success, when i use it in jni ,get error：

### ISSUE THREAD

**Issue by gloddream** [atsushieno/cerbero#5]
file path is correct.

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        new fluidsynth().play("/sdcard/mary.mid","/sdcard/TimGM6mb.sf2");

    }

get error in console:

10-31 18:15:21.426 27495-27495/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
10-31 18:15:21.826 27495-27495/com.example.golddream.myapplication E/fluidsynth: Unable to open file "/sdcard/TimGM6mb.sf2"
10-31 18:15:21.826 27495-27495/com.example.golddream.myapplication E/fluidsynth: Couldn't load soundfont file
10-31 18:15:21.826 27495-27495/com.example.golddream.myapplication E/fluidsynth: Failed to load SoundFont "/sdcard/TimGM6mb.sf2"

**Comment by gloddream** [comment]
i build android fluidsynth.so with the old version:   
is  commit  "5fba0dd"

**Comment by atsushieno** [comment]
A quick answer or workaround is: you need new_fluid_file_stream_loader() to load soundfonts from local files.

**Comment by gloddream** [comment]
ok  but new_fluid_file_stream_loader() is not include  in whic i build the source commit "5fba0dd" 。
when build the newest  , then get  error

**Comment by atsushieno** [comment]
Commented on the other issue.

**Comment by gloddream** [comment]
i change commit to "2d5069f"， the build so  works well。
but still get error：
11-01 17:23:12.532 17940-17940/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Failed to open File or Stream: /sdcard/TimGM6mb.sf2
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Unable to open file "/sdcard/TimGM6mb.sf2"
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Couldn't load soundfont file: /sdcard/TimGM6mb.sf2
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Failed to load SoundFont "/sdcard/TimGM6mb.sf2"

**Comment by gloddream** [comment]
after remove the codes of assert .  now could build  so  successfully。
but the error is still there。
"Unable to open file "/sdcard/TimGM6mb.sf2""

1、git clone https://github.com/atsushieno/android-fluidsynth.git
2、export PATH=$PATH:~/android-fluidsynth/build/android-ndk-r15b
3、make prepare
4、make
5、make buildone-cerbero

**Comment by atsushieno** [comment]
Is that file accessible from within your app e.g. using java,io API ?

**Comment by gloddream** [comment]
thanks 
android 6.0 need open the android.permission of "sdcard" manual

**Comment by atsushieno** [comment]
np, I suspected that ;-)
